---
- name: create war file
  hosts: db
  become: yes

  roles:
   - install-package
   - make-warfile


- name: install tomcat and run war file
  hosts: web
  become: yes

  roles:
   - tomcat-server

  tasks:
  - name: Synchronization
    synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /var/lib/tomcat8/webapps/
    delegate_to: ec2-3-17-73-73.us-east-2.compute.amazonaws.com   


